### ISSUE TITLE
Questions on  acc_te,acc_te_snt

### ISSUE THREAD

**Issue by Sathiyakugan** [grausof/keras-sincnet#11]
Since I couldn't find a contact of you, I am creating this question as an issue, 
 acc_te=0.503742 acc_te_snt=0.966089
what does it mean?
acc_te=0.503742 seems to be very low? What's the conclusion on it?

**Comment by grausof** [comment]
acc_te is the accuracy on the single audio sample (cw_len) of 200ms. acc_te_snt is the accuracy over the entire sentence!

**Comment by Sathiyakugan** [comment]
so the error mentioned in the sincnet is based on the single audio sample isn't it ?
