### ISSUE TITLE
The pretrained mdoel

### ISSUE THREAD

**Issue by pangwenfeng** [grausof/keras-sincnet#2]
Hi, thank you for your code. I use your code to train a model with the dataset timit, but the performance is not as good as I expect. So I want to know whether the author can offer a pretrained model so that we can check this model directly.  Thank you.

**Comment by grausof** [comment]
The performances reported in the README are the same achieved by using the code present in the [train.py](https://github.com/grausof/keras-sincnet/blob/master/train.py) file. Make sure the dataset is correct and you have preprocessed the data.
